apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::697076424099:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-HzDOb93OrUhP
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::697076424099:user/varun
      username: varun      
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::697076424099:user/advi
      username: advi   
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::697076424099:user/pavvi
      username: pavvi  
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::697076424099:user/rakesh
      username: rakesh  
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-19T05:43:44Z"
  name: aws-auth
  namespace: kube-system
  uid: fc15fd5b-0b6e-4e39-ae6b-f1ce35b9f167
